DROP DATABASE IF EXISTS MELHOUSE;
CREATE DATABASE MELHOUSE;
USE MELHOUSE;

SELECT * FROM location;
SELECT * FROM property;
SELECT * FROM house_details;
SELECT * FROM seller;
SELECT * FROM sale;



DROP DATABASE IF EXISTS MELHOUSE_DDL;
CREATE DATABASE MELHOUSE_DDL;
USE MELHOUSE_DDL;
select * from fact_dim;
select * from seller_dim;